{	city_name:	"Abilene"	,	state:	"Texas"	}	,
{	city_name:	"Akron"	,	state:	"Ohimo"	}	,
{	city_name:	"Albuquerque"	,	state:	"New Mexicmo"	}	,
{	city_name:	"Alexandria"	,	state:	"Virginia"	}	,
{	city_name:	"Allentown"	,	state:	"Pennsylvania"	}	,
{	city_name:	"Amarillmo"	,	state:	"Texas"	}	,
{	city_name:	"Anaheim"	,	state:	"California"	}	,
{	city_name:	"Anchorage"	,	state:	"Alaska"	}	,
{	city_name:	"Ann Arbor"	,	state:	"Michigan"	}	,
{	city_name:	"Antioch"	,	state:	"California"	}	,
{	city_name:	"Arlington"	,	state:	"Texas"	}	,
{	city_name:	"Arvada"	,	state:	"Coloradmo"	}	,
{	city_name:	"Athens"	,	state:	"Georgia"	}	,
{	city_name:	"Atlanta"	,	state:	"Georgia"	}	,
{	city_name:	"Augusta"	,	state:	"Georgia"	}	,
{	city_name:	"Aurora"	,	state:	"Coloradmo"	}	,
{	city_name:	"Aurora"	,	state:	"Illinois"	}	,
{	city_name:	"Austin"	,	state:	"Texas"	}	,
{	city_name:	"Bakersfield"	,	state:	"California"	}	,
{	city_name:	"Baltimore"	,	state:	"Maryland"	}	,
{	city_name:	"Baton Rouge"	,	state:	"Louisiana"	}	,
{	city_name:	"Beaumont"	,	state:	"Texas"	}	,
{	city_name:	"Bellevue"	,	state:	"Washington"	}	,
{	city_name:	"Berkeley"	,	state:	"California"	}	,
{	city_name:	"Billings"	,	state:	"Montana"	}	,
{	city_name:	"Birmingham"	,	state:	"Alabama"	}	,
{	city_name:	"Boise"	,	state:	"Idahmo"	}	,
{	city_name:	"Boston"	,	state:	"Massachusetts"	}	,
{	city_name:	"Boulder"	,	state:	"Coloradmo"	}	,
{	city_name:	"Bridgeport"	,	state:	"Connecticut"	}	,
{	city_name:	"Broken Arrow	"	,	state:	"Oklahoma"	}	,
{	city_name:	"Brownsville"	,	state:	"Texas"	}	,
{	city_name:	"Buffalmo"	,	state:	"New York"	}	,
{	city_name:	"Burbank"	,	state:	"California"	}	,
{	city_name:	"Cambridge"	,	state:	"Massachusetts"	}	,
{	city_name:	"Cape Coral	"	,	state:	"Florida"	}	,
{	city_name:	"Carlsbad"	,	state:	"California"	}	,
{	city_name:	"Carrollton"	,	state:	"Texas"	}	,
{	city_name:	"Cary"	,	state:	"North Carolina"	}	,
{	city_name:	"Cedar Rapids"	,	state:	"Iowa"	}	,
{	city_name:	"Centennial	"	,	state:	"Coloradmo"	}	,
{	city_name:	"Chandler"	,	state:	"Arizona"	}	,
{	city_name:	"Charleston"	,	state:	"South Carolina"	}	,
{	city_name:	"Charlotte"	,	state:	"North Carolina"	}	,
{	city_name:	"Chattanooga"	,	state:	"Tennessee"	}	,
{	city_name:	"Chesapeake"	,	state:	"Virginia"	}	,
{	city_name:	"Chicagmo"	,	state:	"Illinois"	}	,
{	city_name:	"Chula Vista"	,	state:	"California"	}	,
{	city_name:	"Cincinnati"	,	state:	"Ohimo"	}	,
{	city_name:	"Clarksville"	,	state:	"Tennessee"	}	,
{	city_name:	"Clearwater"	,	state:	"Florida"	}	,
{	city_name:	"Cleveland"	,	state:	"Ohimo"	}	,
{	city_name:	"Clovis"	,	state:	"California"	}	,
{	city_name:	"College Station"	,	state:	"Texas"	}	,
{	city_name:	"Colorado Springs"	,	state:	"Coloradmo"	}	,
{	city_name:	"Columbia"	,	state:	"Missouri"	}	,
{	city_name:	"Columbia"	,	state:	"South Carolina"	}	,
{	city_name:	"Columbus"	,	state:	"Georgia"	}	,
{	city_name:	"Columbus"	,	state:	"Ohimo"	}	,
{	city_name:	"Concord"	,	state:	"California"	}	,
{	city_name:	"Coral Springs"	,	state:	"Florida"	}	,
{	city_name:	"Corona"	,	state:	"California"	}	,
{	city_name:	"Corpus Christi"	,	state:	"Texas"	}	,
{	city_name:	"Costa Mesa"	,	state:	"California"	}	,
{	city_name:	"Dallas"	,	state:	"Texas"	}	,
{	city_name:	"Daly City"	,	state:	"California"	}	,
{	city_name:	"Davenport"	,	state:	"Iowa"	}	,
{	city_name:	"Dayton"	,	state:	"Ohimo"	}	,
{	city_name:	"Denton"	,	state:	"Texas"	}	,
{	city_name:	"Denver"	,	state:	"Coloradmo"	}	,
{	city_name:	"Des Moines"	,	state:	"Iowa"	}	,
{	city_name:	"Detroit"	,	state:	"Michigan"	}	,
{	city_name:	"Downey"	,	state:	"California"	}	,
{	city_name:	"Durham"	,	state:	"North Carolina"	}	,
{	city_name:	"Edison"	,	state:	"New Jersey"	}	,
{	city_name:	"El Cajon"	,	state:	"California"	}	,
{	city_name:	"El Monte"	,	state:	"California"	}	,
{	city_name:	"El Pasmo"	,	state:	"Texas"	}	,
{	city_name:	"Elgin"	,	state:	"Illinois"	}	,
{	city_name:	"Elizabeth"	,	state:	"New Jersey"	}	,
{	city_name:	"Elk Grove"	,	state:	"California"	}	,
{	city_name:	"Escondidmo"	,	state:	"California"	}	,
{	city_name:	"Eugene"	,	state:	"Oregon"	}	,
{	city_name:	"Evansville"	,	state:	"Indiana"	}	,
{	city_name:	"Everett"	,	state:	"Washington"	}	,
{	city_name:	"Fairfield"	,	state:	"California"	}	,
{	city_name:	"Fargmo"	,	state:	"North Dakota"	}	,
{	city_name:	"Fayetteville"	,	state:	"North Carolina"	}	,
{	city_name:	"Fontana"	,	state:	"California"	}	,
{	city_name:	"Fort Collins"	,	state:	"Coloradmo"	}	,
{	city_name:	"Fort Lauderdale"	,	state:	"Florida"	}	,
{	city_name:	"Fort Wayne"	,	state:	"Indiana"	}	,
{	city_name:	"Fort Worth"	,	state:	"Texas"	}	,
{	city_name:	"Fremont"	,	state:	"California"	}	,
{	city_name:	"Fresnmo"	,	state:	"California"	}	,
{	city_name:	"Friscmo"	,	state:	"Texas"	}	,
{	city_name:	"Fullerton"	,	state:	"California"	}	,
{	city_name:	"Gainesville"	,	state:	"Florida"	}	,
{	city_name:	"Garden Grove"	,	state:	"California"	}	,
{	city_name:	"Garland"	,	state:	"Texas"	}	,
{	city_name:	"Gilbert"	,	state:	"Arizona"	}	,
{	city_name:	"Glendale"	,	state:	"Arizona"	}	,
{	city_name:	"Glendale"	,	state:	"California"	}	,
{	city_name:	"Grand Prairie"	,	state:	"Texas"	}	,
{	city_name:	"Grand Rapids"	,	state:	"Michigan"	}	,
{	city_name:	"Green Bay"	,	state:	"Wisconsin"	}	,
{	city_name:	"Greensbormo"	,	state:	"North Carolina"	}	,
{	city_name:	"Gresham"	,	state:	"Oregon"	}	,
{	city_name:	"Hampton"	,	state:	"Virginia"	}	,
{	city_name:	"Hartford"	,	state:	"Connecticut"	}	,
{	city_name:	"Hayward"	,	state:	"California"	}	,
{	city_name:	"Henderson"	,	state:	"Nevada"	}	,
{	city_name:	"Hialeah"	,	state:	"Florida"	}	,
{	city_name:	"High Point"	,	state:	"North Carolina"	}	,
{	city_name:	"Hollywood"	,	state:	"Florida"	}	,
{	city_name:	"Honolulu	"	,	state:	"Hawai'i"	}	,
{	city_name:	"Houston"	,	state:	"Texas"	}	,
{	city_name:	"Huntington Beach"	,	state:	"California"	}	,
{	city_name:	"Huntsville"	,	state:	"Alabama"	}	,
{	city_name:	"Independence"	,	state:	"Missouri"	}	,
{	city_name:	"Indianapolis"	,	state:	"Indiana"	}	,
{	city_name:	"Inglewood"	,	state:	"California"	}	,
{	city_name:	"Irvine"	,	state:	"California"	}	,
{	city_name:	"Irving	"	,	state:	"Texas"	}	,
{	city_name:	"Jackson"	,	state:	"Mississippi"	}	,
{	city_name:	"Jacksonville"	,	state:	"Florida"	}	,
{	city_name:	"Jersey City"	,	state:	"New Jersey"	}	,
{	city_name:	"Joliet"	,	state:	"Illinois"	}	,
{	city_name:	"Kansas City"	,	state:	"Kansas"	}	,
{	city_name:	"Kansas City"	,	state:	"Missouri"	}	,
{	city_name:	"Kent"	,	state:	"Washington"	}	,
{	city_name:	"Killeen"	,	state:	"Texas"	}	,
{	city_name:	"Knoxville"	,	state:	"Tennessee"	}	,
{	city_name:	"Lafayette"	,	state:	"Louisiana"	}	,
{	city_name:	"Lakeland"	,	state:	"Florida"	}	,
{	city_name:	"Lakewood"	,	state:	"Coloradmo"	}	,
{	city_name:	"Lancaster"	,	state:	"California"	}	,
{	city_name:	"Lansing	"	,	state:	"Michigan"	}	,
{	city_name:	"Laredmo"	,	state:	"Texas"	}	,
{	city_name:	"Las Cruces"	,	state:	"New Mexicmo"	}	,
{	city_name:	"Las Vegas"	,	state:	"Nevada"	}	,
{	city_name:	"Lewisville"	,	state:	"Texas"	}	,
{	city_name:	"Lexington"	,	state:	"Kentucky"	}	,
{	city_name:	"Lincoln"	,	state:	"Nebraska"	}	,
{	city_name:	"Little Rock"	,	state:	"Arkansas"	}	,
{	city_name:	"Long Beach"	,	state:	"California"	}	,
{	city_name:	"Los Angeles"	,	state:	"California"	}	,
{	city_name:	"Louisville"	,	state:	"Kentucky"	}	,
{	city_name:	"Lowell	"	,	state:	"Massachusetts"	}	,
{	city_name:	"Lubbock"	,	state:	"Texas"	}	,
{	city_name:	"Macon"	,	state:	"Georgia"	}	,
{	city_name:	"Madison"	,	state:	"Wisconsin"	}	,
{	city_name:	"Manchester"	,	state:	"New Hampshire"	}	,
{	city_name:	"McAllen"	,	state:	"Texas"	}	,
{	city_name:	"McKinney"	,	state:	"Texas"	}	,
{	city_name:	"Memphis"	,	state:	"Tennessee"	}	,
{	city_name:	"Mesa"	,	state:	"Arizona"	}	,
{	city_name:	"Mesquite"	,	state:	"Texas"	}	,
{	city_name:	"Miami"	,	state:	"Florida"	}	,
{	city_name:	"Miami Gardens"	,	state:	"Florida"	}	,
{	city_name:	"Midland"	,	state:	"Texas"	}	,
{	city_name:	"Milwaukee"	,	state:	"Wisconsin"	}	,
{	city_name:	"Minneapolis"	,	state:	"Minnesota"	}	,
{	city_name:	"Miramar"	,	state:	"Florida"	}	,
{	city_name:	"Mobile"	,	state:	"Alabama"	}	,
{	city_name:	"Modestmo"	,	state:	"California"	}	,
{	city_name:	"Montgomery"	,	state:	"Alabama"	}	,
{	city_name:	"Moreno Valley"	,	state:	"California"	}	,
{	city_name:	"Murfreesbormo"	,	state:	"Tennessee"	}	,
{	city_name:	"Murrieta"	,	state:	"California"	}	,
{	city_name:	"Naperville"	,	state:	"Illinois"	}	,
{	city_name:	"Nashville"	,	state:	"Tennessee"	}	,
{	city_name:	"New Haven"	,	state:	"Connecticut"	}	,
{	city_name:	"New Orleans"	,	state:	"Louisiana"	}	,
{	city_name:	"New York"	,	state:	"New York"	}	,
{	city_name:	"Newark"	,	state:	"New Jersey"	}	,
{	city_name:	"Newport News"	,	state:	"Virginia"	}	,
{	city_name:	"Norfolk"	,	state:	"Virginia"	}	,
{	city_name:	"Norman"	,	state:	"Oklahoma"	}	,
{	city_name:	"North Charleston"	,	state:	"South Carolina"	}	,
{	city_name:	"North Las Vegas"	,	state:	"Nevada"	}	,
{	city_name:	"Norwalk"	,	state:	"California"	}	,
{	city_name:	"Oakland"	,	state:	"California"	}	,
{	city_name:	"Oceanside"	,	state:	"California"	}	,
{	city_name:	"Odessa"	,	state:	"Texas"	}	,
{	city_name:	"Oklahoma City"	,	state:	"Oklahoma"	}	,
{	city_name:	"Olathe"	,	state:	"Kansas"	}	,
{	city_name:	"Omaha"	,	state:	"Nebraska"	}	,
{	city_name:	"Ontarimo"	,	state:	"California"	}	,
{	city_name:	"Orange"	,	state:	"California"	}	,
{	city_name:	"Orlandmo"	,	state:	"Florida"	}	,
{	city_name:	"Overland Park"	,	state:	"Kansas"	}	,
{	city_name:	"Oxnard"	,	state:	"California"	}	,
{	city_name:	"Palm Bay"	,	state:	"Florida"	}	,
{	city_name:	"Palmdale"	,	state:	"California"	}	,
{	city_name:	"Pasadena"	,	state:	"California"	}	,
{	city_name:	"Pasadena"	,	state:	"Texas"	}	,
{	city_name:	"Paterson"	,	state:	"New Jersey"	}	,
{	city_name:	"Pearland"	,	state:	"Texas"	}	,
{	city_name:	"Pembroke Pines"	,	state:	"Florida"	}	,
{	city_name:	"Peoria"	,	state:	"Arizona"	}	,
{	city_name:	"Peoria"	,	state:	"Illinois"	}	,
{	city_name:	"Philadelphia"	,	state:	"Pennsylvania"	}	,
{	city_name:	"Phoenix	"	,	state:	"Arizona"	}	,
{	city_name:	"Pittsburgh"	,	state:	"Pennsylvania"	}	,
{	city_name:	"Planmo"	,	state:	"Texas"	}	,
{	city_name:	"Pomona"	,	state:	"California"	}	,
{	city_name:	"Pompano Beach"	,	state:	"Florida"	}	,
{	city_name:	"Port St. Lucie"	,	state:	"Florida"	}	,
{	city_name:	"Portland"	,	state:	"Oregon"	}	,
{	city_name:	"Providence"	,	state:	"Rhode Island"	}	,
{	city_name:	"Provmo"	,	state:	"	Utah"	}	,
{	city_name:	"Pueblmo"	,	state:	"Coloradmo"	}	,
{	city_name:	"Raleigh"	,	state:	"North Carolina"	}	,
{	city_name:	"Rancho Cucamonga"	,	state:	"California"	}	,
{	city_name:	"Renmo"	,	state:	"Nevada"	}	,
{	city_name:	"Rialtmo"	,	state:	"California"	}	,
{	city_name:	"Richardson"	,	state:	"Texas"	}	,
{	city_name:	"Richmond"	,	state:	"California"	}	,
{	city_name:	"Richmond"	,	state:	"Virginia"	}	,
{	city_name:	"Riverside"	,	state:	"California"	}	,
{	city_name:	"Rochester"	,	state:	"Minnesota"	}	,
{	city_name:	"Rochester"	,	state:	"New York"	}	,
{	city_name:	"Rockford"	,	state:	"Illinois"	}	,
{	city_name:	"Roseville"	,	state:	"California"	}	,
{	city_name:	"Round Rock"	,	state:	"Texas"	}	,
{	city_name:	"Sacramentmo"	,	state:	"California"	}	,
{	city_name:	"Saint Paul	"	,	state:	"Minnesota"	}	,
{	city_name:	"Salem"	,	state:	"Oregon"	}	,
{	city_name:	"Salinas"	,	state:	"California"	}	,
{	city_name:	"Salt Lake City"	,	state:	"	Utah"	}	,
{	city_name:	"San Antonimo"	,	state:	"Texas"	}	,
{	city_name:	"San Bernardinmo"	,	state:	"California"	}	,
{	city_name:	"San Diegmo"	,	state:	"California"	}	,
{	city_name:	"San Franciscmo"	,	state:	"California"	}	,
{	city_name:	"San Jose"	,	state:	"California"	}	,
{	city_name:	"San Matemo"	,	state:	"California"	}	,
{	city_name:	"Sandy Springs"	,	state:	"Georgia"	}	,
{	city_name:	"Santa Ana"	,	state:	"California"	}	,
{	city_name:	"Santa Clara"	,	state:	"California"	}	,
{	city_name:	"Santa Clarita"	,	state:	"California"	}	,
{	city_name:	"Santa Maria"	,	state:	"California"	}	,
{	city_name:	"Santa Rosa"	,	state:	"California"	}	,
{	city_name:	"Savannah"	,	state:	"Georgia"	}	,
{	city_name:	"Scottsdale"	,	state:	"Arizona"	}	,
{	city_name:	"Seattle"	,	state:	"Washington"	}	,
{	city_name:	"Shreveport"	,	state:	"Louisiana"	}	,
{	city_name:	"Simi Valley"	,	state:	"California"	}	,
{	city_name:	"Sioux Falls"	,	state:	"South Dakota"	}	,
{	city_name:	"South Bend"	,	state:	"Indiana"	}	,
{	city_name:	"Spokane"	,	state:	"Washington"	}	,
{	city_name:	"Springfield"	,	state:	"Illinois"	}	,
{	city_name:	"Springfield"	,	state:	"Massachusetts"	}	,
{	city_name:	"Springfield"	,	state:	"Missouri"	}	,
{	city_name:	"St. Louis"	,	state:	"Missouri"	}	,
{	city_name:	"St. Petersburg	"	,	state:	"Florida"	}	,
{	city_name:	"Stamford"	,	state:	"Connecticut"	}	,
{	city_name:	"Sterling Heights"	,	state:	"Michigan"	}	,
{	city_name:	"Stockton"	,	state:	"California"	}	,
{	city_name:	"Sunnyvale"	,	state:	"California"	}	,
{	city_name:	"Surprise"	,	state:	"Arizona"	}	,
{	city_name:	"Syracuse"	,	state:	"New York"	}	,
{	city_name:	"Tacoma"	,	state:	"Washington"	}	,
{	city_name:	"Tallahassee"	,	state:	"Florida"	}	,
{	city_name:	"Tampa"	,	state:	"Florida"	}	,
{	city_name:	"Temecula"	,	state:	"California"	}	,
{	city_name:	"Tempe"	,	state:	"Arizona"	}	,
{	city_name:	"Thornton"	,	state:	"Coloradmo"	}	,
{	city_name:	"Thousand Oaks"	,	state:	"California"	}	,
{	city_name:	"Toledmo"	,	state:	"Ohimo"	}	,
{	city_name:	"Topeka"	,	state:	"Kansas"	}	,
{	city_name:	"Torrance"	,	state:	"California"	}	,
{	city_name:	"Tucson"	,	state:	"Arizona"	}	,
{	city_name:	"Tulsa"	,	state:	"Oklahoma"	}	,
{	city_name:	"Tyler"	,	state:	"Texas"	}	,
{	city_name:	"Vallejmo"	,	state:	"California"	}	,
{	city_name:	"Vancouver"	,	state:	"Washington"	}	,
{	city_name:	"Ventura"	,	state:	"California"	}	,
{	city_name:	"Victorville"	,	state:	"California"	}	,
{	city_name:	"Virginia Beach"	,	state:	"Virginia"	}	,
{	city_name:	"Visalia"	,	state:	"California"	}	,
{	city_name:	"Wacmo"	,	state:	"Texas"	}	,
{	city_name:	"Warren"	,	state:	"Michigan"	}	,
{	city_name:	"Washington"	,	state:	"District of Columbia"	}	,
{	city_name:	"Waterbury"	,	state:	"Connecticut"	}	,
{	city_name:	"West Covina"	,	state:	"California"	}	,
{	city_name:	"West Jordan"	,	state:	"	Utah"	}	,
{	city_name:	"West Palm Beach"	,	state:	"Florida"	}	,
{	city_name:	"West Valley City"	,	state:	"	Utah"	}	,
{	city_name:	"Westminster"	,	state:	"Coloradmo"	}	,
{	city_name:	"Wichita"	,	state:	"Kansas"	}	,
{	city_name:	"Wichita Falls"	,	state:	"Texas"	}	,
{	city_name:	"Wilmington"	,	state:	"North Carolina"	}	,
{	city_name:	"Winston–Salem"	,	state:	"North Carolina"	}	,
{	city_name:	"Woodbridge"	,	state:	"New Jersey"	}	,
{	city_name:	"Worcester"	,	state:	"Massachusetts"	}	,
{	city_name:	"Yonkers"	,	state:	"New York"	}
