{	city_name:	"	Birmingham	"	,	state:	"	Alabama	"	}	,
{	city_name:	"	Montgomery	"	,	state:	"	Alabama	"	}	,
{	city_name:	"	Mobile	"	,	state:	"	Alabama	"	}	,
{	city_name:	"	Huntsville	"	,	state:	"	Alabama	"	}	,
{	city_name:	"	Anchorage	"	,	state:	"	Alaska	"	}	,
{	city_name:	"	Phoenix	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Tucson	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Mesa	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Chandler	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Gilbert	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Glendale	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Scottsdale	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Tempe	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Peoria	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Surprise	"	,	state:	"	Arizona	"	}	,
{	city_name:	"	Little Rock	"	,	state:	"	Arkansas	"	}	,
{	city_name:	"	Los Angeles	"	,	state:	"	California	"	}	,
{	city_name:	"	San Diego	"	,	state:	"	California	"	}	,
{	city_name:	"	San Jose	"	,	state:	"	California	"	}	,
{	city_name:	"	San Francisco	"	,	state:	"	California	"	}	,
{	city_name:	"	Fresno	"	,	state:	"	California	"	}	,
{	city_name:	"	Sacramento	"	,	state:	"	California	"	}	,
{	city_name:	"	Long Beach	"	,	state:	"	California	"	}	,
{	city_name:	"	Oakland	"	,	state:	"	California	"	}	,
{	city_name:	"	Bakersfield	"	,	state:	"	California	"	}	,
{	city_name:	"	Anaheim	"	,	state:	"	California	"	}	,
{	city_name:	"	Santa Ana	"	,	state:	"	California	"	}	,
{	city_name:	"	Riverside	"	,	state:	"	California	"	}	,
{	city_name:	"	Stockton	"	,	state:	"	California	"	}	,
{	city_name:	"	Chula Vista	"	,	state:	"	California	"	}	,
{	city_name:	"	Irvine	"	,	state:	"	California	"	}	,
{	city_name:	"	Fremont	"	,	state:	"	California	"	}	,
{	city_name:	"	San Bernardino	"	,	state:	"	California	"	}	,
{	city_name:	"	Modesto	"	,	state:	"	California	"	}	,
{	city_name:	"	Oxnard	"	,	state:	"	California	"	}	,
{	city_name:	"	Fontana	"	,	state:	"	California	"	}	,
{	city_name:	"	Moreno Valley	"	,	state:	"	California	"	}	,
{	city_name:	"	Huntington Beach	"	,	state:	"	California	"	}	,
{	city_name:	"	Glendale	"	,	state:	"	California	"	}	,
{	city_name:	"	Santa Clarita	"	,	state:	"	California	"	}	,
{	city_name:	"	Garden Grove	"	,	state:	"	California	"	}	,
{	city_name:	"	Oceanside	"	,	state:	"	California	"	}	,
{	city_name:	"	Rancho Cucamonga	"	,	state:	"	California	"	}	,
{	city_name:	"	Santa Rosa	"	,	state:	"	California	"	}	,
{	city_name:	"	Ontario	"	,	state:	"	California	"	}	,
{	city_name:	"	Elk Grove	"	,	state:	"	California	"	}	,
{	city_name:	"	Corona	"	,	state:	"	California	"	}	,
{	city_name:	"	Lancaster	"	,	state:	"	California	"	}	,
{	city_name:	"	Palmdale	"	,	state:	"	California	"	}	,
{	city_name:	"	Salinas	"	,	state:	"	California	"	}	,
{	city_name:	"	Hayward	"	,	state:	"	California	"	}	,
{	city_name:	"	Pomona	"	,	state:	"	California	"	}	,
{	city_name:	"	Escondido	"	,	state:	"	California	"	}	,
{	city_name:	"	Sunnyvale	"	,	state:	"	California	"	}	,
{	city_name:	"	Torrance	"	,	state:	"	California	"	}	,
{	city_name:	"	Pasadena	"	,	state:	"	California	"	}	,
{	city_name:	"	Orange	"	,	state:	"	California	"	}	,
{	city_name:	"	Fullerton	"	,	state:	"	California	"	}	,
{	city_name:	"	Thousand Oaks	"	,	state:	"	California	"	}	,
{	city_name:	"	Visalia	"	,	state:	"	California	"	}	,
{	city_name:	"	Roseville	"	,	state:	"	California	"	}	,
{	city_name:	"	Concord	"	,	state:	"	California	"	}	,
{	city_name:	"	Simi Valley	"	,	state:	"	California	"	}	,
{	city_name:	"	Santa Clara	"	,	state:	"	California	"	}	,
{	city_name:	"	Victorville	"	,	state:	"	California	"	}	,
{	city_name:	"	Vallejo	"	,	state:	"	California	"	}	,
{	city_name:	"	Berkeley	"	,	state:	"	California	"	}	,
{	city_name:	"	El Monte	"	,	state:	"	California	"	}	,
{	city_name:	"	Downey	"	,	state:	"	California	"	}	,
{	city_name:	"	Costa Mesa	"	,	state:	"	California	"	}	,
{	city_name:	"	Carlsbad	"	,	state:	"	California	"	}	,
{	city_name:	"	Inglewood	"	,	state:	"	California	"	}	,
{	city_name:	"	Fairfield	"	,	state:	"	California	"	}	,
{	city_name:	"	Ventura	"	,	state:	"	California	"	}	,
{	city_name:	"	Temecula	"	,	state:	"	California	"	}	,
{	city_name:	"	Antioch	"	,	state:	"	California	"	}	,
{	city_name:	"	Richmond	"	,	state:	"	California	"	}	,
{	city_name:	"	West Covina	"	,	state:	"	California	"	}	,
{	city_name:	"	Murrieta	"	,	state:	"	California	"	}	,
{	city_name:	"	Norwalk	"	,	state:	"	California	"	}	,
{	city_name:	"	Daly City	"	,	state:	"	California	"	}	,
{	city_name:	"	Burbank	"	,	state:	"	California	"	}	,
{	city_name:	"	Santa Maria	"	,	state:	"	California	"	}	,
{	city_name:	"	El Cajon	"	,	state:	"	California	"	}	,
{	city_name:	"	San Mateo	"	,	state:	"	California	"	}	,
{	city_name:	"	Rialto	"	,	state:	"	California	"	}	,
{	city_name:	"	Clovis	"	,	state:	"	California	"	}	,
{	city_name:	"	Denver	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Colorado Springs	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Aurora	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Fort Collins	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Lakewood	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Thornton	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Arvada	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Westminster	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Pueblo	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Centennial	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Boulder	"	,	state:	"	Colorado	"	}	,
{	city_name:	"	Bridgeport	"	,	state:	"	Connecticut	"	}	,
{	city_name:	"	New Haven	"	,	state:	"	Connecticut	"	}	,
{	city_name:	"	Stamford	"	,	state:	"	Connecticut	"	}	,
{	city_name:	"	Hartford	"	,	state:	"	Connecticut	"	}	,
{	city_name:	"	Waterbury	"	,	state:	"	Connecticut	"	}	,
{	city_name:	"	Washington	"	,	state:	"	District of Columbia	"	}	,
{	city_name:	"	Jacksonville	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Miami	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Tampa	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Orlando	"	,	state:	"	Florida	"	}	,
{	city_name:	"	St. Petersburg	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Hialeah	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Tallahassee	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Fort Lauderdale	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Port St. Lucie	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Cape Coral	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Pembroke Pines	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Hollywood	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Miramar	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Gainesville	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Coral Springs	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Miami Gardens	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Clearwater	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Pompano Beach	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Palm Bay	"	,	state:	"	Florida	"	}	,
{	city_name:	"	West Palm Beach	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Lakeland	"	,	state:	"	Florida	"	}	,
{	city_name:	"	Atlanta	"	,	state:	"	Georgia	"	}	,
{	city_name:	"	Columbus	"	,	state:	"	Georgia	"	}	,
{	city_name:	"	Augusta	"	,	state:	"	Georgia	"	}	,
{	city_name:	"	Macon	"	,	state:	"	Georgia	"	}	,
{	city_name:	"	Savannah	"	,	state:	"	Georgia	"	}	,
{	city_name:	"	Athens	"	,	state:	"	Georgia	"	}	,
{	city_name:	"	Sandy Springs	"	,	state:	"	Georgia	"	}	,
{	city_name:	"	Honolulu	"	,	state:	"	Hawai'i	"	}	,
{	city_name:	"	Boise	"	,	state:	"	Idaho	"	}	,
{	city_name:	"	Chicago	"	,	state:	"	Illinois	"	}	,
{	city_name:	"	Aurora	"	,	state:	"	Illinois	"	}	,
{	city_name:	"	Rockford	"	,	state:	"	Illinois	"	}	,
{	city_name:	"	Joliet	"	,	state:	"	Illinois	"	}	,
{	city_name:	"	Naperville	"	,	state:	"	Illinois	"	}	,
{	city_name:	"	Springfield	"	,	state:	"	Illinois	"	}	,
{	city_name:	"	Peoria	"	,	state:	"	Illinois	"	}	,
{	city_name:	"	Elgin	"	,	state:	"	Illinois	"	}	,
{	city_name:	"	Indianapolis	"	,	state:	"	Indiana	"	}	,
{	city_name:	"	Fort Wayne	"	,	state:	"	Indiana	"	}	,
{	city_name:	"	Evansville	"	,	state:	"	Indiana	"	}	,
{	city_name:	"	South Bend	"	,	state:	"	Indiana	"	}	,
{	city_name:	"	Des Moines	"	,	state:	"	Iowa	"	}	,
{	city_name:	"	Cedar Rapids	"	,	state:	"	Iowa	"	}	,
{	city_name:	"	Davenport	"	,	state:	"	Iowa	"	}	,
{	city_name:	"	Wichita	"	,	state:	"	Kansas	"	}	,
{	city_name:	"	Overland Park	"	,	state:	"	Kansas	"	}	,
{	city_name:	"	Kansas City	"	,	state:	"	Kansas	"	}	,
{	city_name:	"	Olathe	"	,	state:	"	Kansas	"	}	,
{	city_name:	"	Topeka	"	,	state:	"	Kansas	"	}	,
{	city_name:	"	Louisville	"	,	state:	"	Kentucky	"	}	,
{	city_name:	"	Lexington	"	,	state:	"	Kentucky	"	}	,
{	city_name:	"	New Orleans	"	,	state:	"	Louisiana	"	}	,
{	city_name:	"	Baton Rouge	"	,	state:	"	Louisiana	"	}	,
{	city_name:	"	Shreveport	"	,	state:	"	Louisiana	"	}	,
{	city_name:	"	Lafayette	"	,	state:	"	Louisiana	"	}	,
{	city_name:	"	Baltimore	"	,	state:	"	Maryland	"	}	,
{	city_name:	"	Boston	"	,	state:	"	Massachusetts	"	}	,
{	city_name:	"	Worcester	"	,	state:	"	Massachusetts	"	}	,
{	city_name:	"	Springfield	"	,	state:	"	Massachusetts	"	}	,
{	city_name:	"	Lowell	"	,	state:	"	Massachusetts	"	}	,
{	city_name:	"	Cambridge	"	,	state:	"	Massachusetts	"	}	,
{	city_name:	"	Detroit	"	,	state:	"	Michigan	"	}	,
{	city_name:	"	Grand Rapids	"	,	state:	"	Michigan	"	}	,
{	city_name:	"	Warren	"	,	state:	"	Michigan	"	}	,
{	city_name:	"	Sterling Heights	"	,	state:	"	Michigan	"	}	,
{	city_name:	"	Ann Arbor	"	,	state:	"	Michigan	"	}	,
{	city_name:	"	Lansing	"	,	state:	"	Michigan	"	}	,
{	city_name:	"	Minneapolis	"	,	state:	"	Minnesota	"	}	,
{	city_name:	"	Saint Paul	"	,	state:	"	Minnesota	"	}	,
{	city_name:	"	Rochester	"	,	state:	"	Minnesota	"	}	,
{	city_name:	"	Jackson	"	,	state:	"	Mississippi	"	}	,
{	city_name:	"	Kansas City	"	,	state:	"	Missouri	"	}	,
{	city_name:	"	St. Louis	"	,	state:	"	Missouri	"	}	,
{	city_name:	"	Springfield	"	,	state:	"	Missouri	"	}	,
{	city_name:	"	Independence	"	,	state:	"	Missouri	"	}	,
{	city_name:	"	Columbia	"	,	state:	"	Missouri	"	}	,
{	city_name:	"	Billings	"	,	state:	"	Montana	"	}	,
{	city_name:	"	Omaha	"	,	state:	"	Nebraska	"	}	,
{	city_name:	"	Lincoln	"	,	state:	"	Nebraska	"	}	,
{	city_name:	"	Las Vegas	"	,	state:	"	Nevada	"	}	,
{	city_name:	"	Henderson	"	,	state:	"	Nevada	"	}	,
{	city_name:	"	Reno	"	,	state:	"	Nevada	"	}	,
{	city_name:	"	North Las Vegas	"	,	state:	"	Nevada	"	}	,
{	city_name:	"	Manchester	"	,	state:	"	New Hampshire	"	}	,
{	city_name:	"	Newark	"	,	state:	"	New Jersey	"	}	,
{	city_name:	"	Jersey City	"	,	state:	"	New Jersey	"	}	,
{	city_name:	"	Paterson	"	,	state:	"	New Jersey	"	}	,
{	city_name:	"	Elizabeth	"	,	state:	"	New Jersey	"	}	,
{	city_name:	"	Edison	"	,	state:	"	New Jersey	"	}	,
{	city_name:	"	Woodbridge	"	,	state:	"	New Jersey	"	}	,
{	city_name:	"	Albuquerque	"	,	state:	"	New Mexico	"	}	,
{	city_name:	"	Las Cruces	"	,	state:	"	New Mexico	"	}	,
{	city_name:	"	New York	"	,	state:	"	New York	"	}	,
{	city_name:	"	Buffalo	"	,	state:	"	New York	"	}	,
{	city_name:	"	Rochester	"	,	state:	"	New York	"	}	,
{	city_name:	"	Yonkers	"	,	state:	"	New York	"	}	,
{	city_name:	"	Syracuse	"	,	state:	"	New York	"	}	,
{	city_name:	"	Charlotte	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	Raleigh	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	Greensboro	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	Durham	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	Winston–Salem	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	Fayetteville	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	Cary	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	Wilmington	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	High Point	"	,	state:	"	North Carolina	"	}	,
{	city_name:	"	Fargo	"	,	state:	"	North Dakota	"	}	,
{	city_name:	"	Columbus	"	,	state:	"	Ohio	"	}	,
{	city_name:	"	Cleveland	"	,	state:	"	Ohio	"	}	,
{	city_name:	"	Cincinnati	"	,	state:	"	Ohio	"	}	,
{	city_name:	"	Toledo	"	,	state:	"	Ohio	"	}	,
{	city_name:	"	Akron	"	,	state:	"	Ohio	"	}	,
{	city_name:	"	Dayton	"	,	state:	"	Ohio	"	}	,
{	city_name:	"	Oklahoma City	"	,	state:	"	Oklahoma	"	}	,
{	city_name:	"	Tulsa	"	,	state:	"	Oklahoma	"	}	,
{	city_name:	"	Norman	"	,	state:	"	Oklahoma	"	}	,
{	city_name:	"	Broken Arrow	"	,	state:	"	Oklahoma	"	}	,
{	city_name:	"	Portland	"	,	state:	"	Oregon	"	}	,
{	city_name:	"	Salem	"	,	state:	"	Oregon	"	}	,
{	city_name:	"	Eugene	"	,	state:	"	Oregon	"	}	,
{	city_name:	"	Gresham	"	,	state:	"	Oregon	"	}	,
{	city_name:	"	Philadelphia	"	,	state:	"	Pennsylvania	"	}	,
{	city_name:	"	Pittsburgh	"	,	state:	"	Pennsylvania	"	}	,
{	city_name:	"	Allentown	"	,	state:	"	Pennsylvania	"	}	,
{	city_name:	"	Providence	"	,	state:	"	Rhode Island	"	}	,
{	city_name:	"	Columbia	"	,	state:	"	South Carolina	"	}	,
{	city_name:	"	Charleston	"	,	state:	"	South Carolina	"	}	,
{	city_name:	"	North Charleston	"	,	state:	"	South Carolina	"	}	,
{	city_name:	"	Sioux Falls	"	,	state:	"	South Dakota	"	}	,
{	city_name:	"	Memphis	"	,	state:	"	Tennessee	"	}	,
{	city_name:	"	Nashville	"	,	state:	"	Tennessee	"	}	,
{	city_name:	"	Knoxville	"	,	state:	"	Tennessee	"	}	,
{	city_name:	"	Chattanooga	"	,	state:	"	Tennessee	"	}	,
{	city_name:	"	Clarksville	"	,	state:	"	Tennessee	"	}	,
{	city_name:	"	Murfreesboro	"	,	state:	"	Tennessee	"	}	,
{	city_name:	"	Houston	"	,	state:	"	Texas	"	}	,
{	city_name:	"	San Antonio	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Dallas	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Austin	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Fort Worth	"	,	state:	"	Texas	"	}	,
{	city_name:	"	El Paso	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Arlington	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Corpus Christi	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Plano	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Laredo	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Lubbock	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Garland	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Irving	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Amarillo	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Grand Prairie	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Brownsville	"	,	state:	"	Texas	"	}	,
{	city_name:	"	McKinney	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Pasadena	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Frisco	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Mesquite	"	,	state:	"	Texas	"	}	,
{	city_name:	"	McAllen	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Killeen	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Waco	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Carrollton	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Denton	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Midland	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Abilene	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Beaumont	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Odessa	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Round Rock	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Richardson	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Wichita Falls	"	,	state:	"	Texas	"	}	,
{	city_name:	"	College Station	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Pearland	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Lewisville	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Tyler	"	,	state:	"	Texas	"	}	,
{	city_name:	"	Salt Lake City	"	,	state:	"	Utah	"	}	,
{	city_name:	"	West Valley City	"	,	state:	"	Utah	"	}	,
{	city_name:	"	Provo	"	,	state:	"	Utah	"	}	,
{	city_name:	"	West Jordan	"	,	state:	"	Utah	"	}	,
{	city_name:	"	Virginia Beach	"	,	state:	"	Virginia	"	}	,
{	city_name:	"	Norfolk	"	,	state:	"	Virginia	"	}	,
{	city_name:	"	Chesapeake	"	,	state:	"	Virginia	"	}	,
{	city_name:	"	Richmond	"	,	state:	"	Virginia	"	}	,
{	city_name:	"	Newport News	"	,	state:	"	Virginia	"	}	,
{	city_name:	"	Alexandria	"	,	state:	"	Virginia	"	}	,
{	city_name:	"	Hampton	"	,	state:	"	Virginia	"	}	,
{	city_name:	"	Seattle	"	,	state:	"	Washington	"	}	,
{	city_name:	"	Spokane	"	,	state:	"	Washington	"	}	,
{	city_name:	"	Tacoma	"	,	state:	"	Washington	"	}	,
{	city_name:	"	Vancouver	"	,	state:	"	Washington	"	}	,
{	city_name:	"	Bellevue	"	,	state:	"	Washington	"	}	,
{	city_name:	"	Kent	"	,	state:	"	Washington	"	}	,
{	city_name:	"	Everett	"	,	state:	"	Washington	"	}	,
{	city_name:	"	Milwaukee	"	,	state:	"	Wisconsin	"	}	,
{	city_name:	"	Madison	"	,	state:	"	Wisconsin	"	}	,
{	city_name:	"	Green Bay	"	,	state:	"	Wisconsin	"	}	,
